package net.avalon.zzz.mapper.generator;

import java.util.List;
import net.avalon.zzz.mapper.generator.po.AgentPo;
import net.avalon.zzz.mapper.generator.po.AgentPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AgentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    long countByExample(AgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int deleteByExample(AgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int insert(AgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int insertSelective(AgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    List<AgentPo> selectByExample(AgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    AgentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") AgentPo row, @Param("example") AgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") AgentPo row, @Param("example") AgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AgentPo row);
}