package net.avalon.zzz.mapper.generator;

import java.util.List;
import net.avalon.zzz.mapper.generator.po.BossPo;
import net.avalon.zzz.mapper.generator.po.BossPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BossPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    long countByExample(BossPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int deleteByExample(BossPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int insert(BossPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int insertSelective(BossPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    List<BossPo> selectByExample(BossPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    BossPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") BossPo row, @Param("example") BossPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") BossPo row, @Param("example") BossPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BossPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BossPo row);
}