package net.avalon.zzz.mapper.generator;

import java.util.List;
import net.avalon.zzz.mapper.generator.po.StagePo;
import net.avalon.zzz.mapper.generator.po.StagePoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StagePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    long countByExample(StagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int deleteByExample(StagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int insert(StagePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int insertSelective(StagePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    List<StagePo> selectByExample(StagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    StagePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StagePo row, @Param("example") StagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StagePo row, @Param("example") StagePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StagePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StagePo row);
}