package net.avalon.zzz.mapper.generator;

import java.util.List;
import net.avalon.zzz.mapper.generator.po.TeamAgentPo;
import net.avalon.zzz.mapper.generator.po.TeamAgentPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TeamAgentPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    long countByExample(TeamAgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int deleteByExample(TeamAgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int insert(TeamAgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int insertSelective(TeamAgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    List<TeamAgentPo> selectByExample(TeamAgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    TeamAgentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TeamAgentPo row, @Param("example") TeamAgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TeamAgentPo row, @Param("example") TeamAgentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeamAgentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeamAgentPo row);
}