
server:
  port: 1000

spring:
  application:
    name: avalon-zzz
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    #JDBC驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库服务器url
    url: jdbc:mysql://localhost:3306/avalon_zzz?serverTimezone=Asia/Shanghai
    #数据库服务器用户名和密码
    username: root
    password: Hd15364514749+
#    password: Hd15364514749+
    #数据库连接池
    type: com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceWrapper
    druid:
      #初始化时与 Mysql 建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      validation-query: select 1
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码
      password: 123456
      #连接池最大连接数（使用负值表示没有限制）
      lettuce:
        pool:
          max-active: 100
          # 连接池中的最大空闲连接
          max-idle: 100
          # 连接池中的最小空闲连接
          min-idle: 0
          #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
      # 连接超时时间（毫秒）
      timeout: 5000

logging:
  charset:
    console: utf-8
  level:
    root: debug

file:
  targetDir: C:/zzz-file