package net.avalon.zzz.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   关卡
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table level
 */
@Data
public class LevelPo {
    private Long id;

    /**
     * Database Column Remarks:
     *   关卡类型
     */
    private String name;

    /**
     * Database Column Remarks:
     *   0-正常（默认）、1-已删除
     */
    private Byte deleted;

    private LocalDateTime createTime;

    private Long createBy;

    private LocalDateTime updateTime;

    private Long updateBy;


}