package net.avalon.zzz.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   队伍
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team
 */
@Data
public class TeamPo {
    private Long id;

    /**
     * Database Column Remarks:
     *   队伍名称
     */
    private String name;

    /**
     * Database Column Remarks:
     *   视频 id
     */
    private Long videoId;

    /**
     * Database Column Remarks:
     *   0-正常（默认）、1-已删除
     */
    private Byte deleted;

    private LocalDateTime createTime;

    private Long createBy;

    private LocalDateTime updateTime;

    private Long updateBy;


}