package net.avalon.zzz.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   队伍-代理人
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team_agent
 */
@Data
public class TeamAgentPo {
    private Long id;

    /**
     * Database Column Remarks:
     *   队伍 id
     */
    private Long teamId;

    /**
     * Database Column Remarks:
     *   代理人 id
     */
    private Long agentId;

    /**
     * Database Column Remarks:
     *   0-正常（默认）、1-已删除
     */
    private Byte deleted;

    private LocalDateTime createTime;

    private Long createBy;

    private LocalDateTime updateTime;

    private Long updateBy;


}