package net.avalon.zzz.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   视频表（video）
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table video
 */
@Data
public class VideoPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   关卡名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.stage_name
     *
     * @mbg.generated
     */
    private String stageName;

    /**
     * Database Column Remarks:
     *   视频地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   状态。
     *   0：审核中（默认）、1：审核通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   Action By
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.action_by
     *
     * @mbg.generated
     */
    private String actionBy;

    /**
     * Database Column Remarks:
     *   关卡类型 id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.stage_id
     *
     * @mbg.generated
     */
    private Long stageId;

    /**
     * Database Column Remarks:
     *   删除。0：还在、1：已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.deleted
     *
     * @mbg.generated
     */
    private Byte deleted;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.stage_name
     *
     * @return the value of video.stage_name
     *
     * @mbg.generated
     */
    public String getStageName() {
        return stageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.stage_name
     *
     * @param stageName the value for video.stage_name
     *
     * @mbg.generated
     */
    public void setStageName(String stageName) {
        this.stageName = stageName == null ? null : stageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.address
     *
     * @return the value of video.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.address
     *
     * @param address the value for video.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.status
     *
     * @return the value of video.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.status
     *
     * @param status the value for video.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.action_by
     *
     * @return the value of video.action_by
     *
     * @mbg.generated
     */
    public String getActionBy() {
        return actionBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.action_by
     *
     * @param actionBy the value for video.action_by
     *
     * @mbg.generated
     */
    public void setActionBy(String actionBy) {
        this.actionBy = actionBy == null ? null : actionBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.stage_id
     *
     * @return the value of video.stage_id
     *
     * @mbg.generated
     */
    public Long getStageId() {
        return stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.stage_id
     *
     * @param stageId the value for video.stage_id
     *
     * @mbg.generated
     */
    public void setStageId(Long stageId) {
        this.stageId = stageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.deleted
     *
     * @return the value of video.deleted
     *
     * @mbg.generated
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.deleted
     *
     * @param deleted the value for video.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.create_time
     *
     * @return the value of video.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.create_time
     *
     * @param createTime the value for video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.update_time
     *
     * @return the value of video.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.update_time
     *
     * @param updateTime the value for video.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}