package net.avalon.zzz.mapper.generator.po;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   视频
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table video
 */
@Data
public class VideoPo {
    private Long id;

    /**
     * Database Column Remarks:
     *   标题
     */
    private String title;

    /**
     * Database Column Remarks:
     *   关卡名称
     */
    private String levelName;

    /**
     * Database Column Remarks:
     *   视频地址
     */
    private String address;

    /**
     * Database Column Remarks:
     *   状态：0 - 审核中（默认）、1 - 审核通过、2 - 审核未通过
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   Action By
     */
    private String actionBy;

    /**
     * Database Column Remarks:
     *   关卡类型 id
     */
    private Long levelId;

    /**
     * Database Column Remarks:
     *   0-正常（默认）、1-已删除
     */
    private Byte deleted;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   创建者
     */
    private Long createBy;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   更新者
     */
    private Long updateBy;


}